#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/masterlayout.sh
bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

bspc rule -a Zathura state=tiled

#Configs side of monitors BSPWM
SECOND_MONITOR_SIDE="left"
THIRD_MONITOR_SIDE="rigth"

#Get Monitors
PRINCIPAL=$(xrandr | grep primary | awk '{print $1}')
SECOND_MONITOR=$(xrandr | grep connected | awk '{i++}i==2'| awk '{print $1}')
THIRD_MONITOR=$(xrandr | grep connected | awk '{i++}i==3'| awk '{print $1}')

sxhkd &

 Configure Monitors
if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "3" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V
  bspc monitor $(bspc query -M | sed -n 2p) -d VI VII VIII IX X
  bspc monitor $(bspc query -M | sed -n 3p) -d XI XII XIII XIV XV
  Set Monitors Side and output
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL
  xrandr --output $THIRD_MONITOR --$THIRD_MONITOR_SIDE-of $PRINCIPAL
elif [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V
  bspc monitor $(bspc query -M | sed -n 2p) -d VI VII VIII IX X
  #Set Monitors Side and output
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL
else
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc monitor HDMI-A-0 -d 1 2 3 4 &
bspc monitor eDP -d 5 6 7 8 9 &

bspc config border_width 4
bspc config normal_border_color "#32344a"
bspc config focused_border_color "#787c99"

bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled
