#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 100 		# Set DPI. User may want to use a larger number for larger screens.
autorandr --load default &
setbg --change-colors &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
xidlehook --not-when-audio --not-when-fullscreen --timer 1800 'systemctl suspend' '' &


# rclone mount --daemon gdrive: ~/gdrive &
# rclone mount --daemon gphotos: ~/Pictures/gphotos/ &




autostart="mpd xcompmgr dunst unclutter"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"


# redshift
temperature-redshift &
